export const projectItems = [
  {
    id: 0,
    category: "webflew",
    img: "/project-1.png",
    name: "Demo Design Project",
    link: "https://jagadishs-proventus.webflow.io/",
  },
  {
    id: 1,
    category: "react",
    img: "/project-2.png",
    name: "Web Calculator",
    link: "https://jagadish-web-calculator.netlify.app/",
  },
  {
    id: 2,
    category: "react",
    img: "/project5.png",
    name: "Card Desigen",
    link: "",
  },
  {
    id: 3,
    category: "uiux",
    img: "/project6.png",
    name: "ui design",
    link: "",
  },
  {
    id: 4,
    category: "javascript",
    img: "/project7.jpg",
    name: "js font page",
    link: "",
  },
  {
    id: 5,
    category: "javascript",
    img: "/project8.jpg",
    name: "UI/UX Design",
    link: "",
  },
  {
    id: 6,
    category: "typescript",
    img: "/project9.jpg",
    name: "Calculator",
    link: "",
  },
  {
    id: 7,
    category: "javascript",
    img: "/project1.jpg",
    name: "Calculator",
    description: "its our Calculator Project",
    link: "",
  },
  {
    id: 8,
    category: "react",
    img: "/pr1.png",
    name: "Design",
    link: "",
  },
];
