export const projectItems = [
  {
    id: 0,
    category: "webflew",
    img: "/project-1.png",
    name: "Demo Design Project",
    link: "https://jagadishs-proventus.webflow.io/",
  },
  {
    id: 1,
    category: "react",
    img: "/project-2.png",
    name: "Web Calculator",
    link: "https://jagadish-web-calculator.netlify.app/",
  },
  {
    id: 2,
    category: "react",
    img: "/webartizen.png",
    name: "Web Artizen",
    link: "https://jagadishwebartizen.netlify.app/",
  },
  {
    id: 3,
    category: "react",
    img: "/dantalcare.png",
    name: "Roots Dental Care",
    link: "https://jagadishdentalcare.netlify.app/",
  },
  {
    id: 4,
    category: "react",
    img: "/e-comarce-1.png",
    name: "E-Comarce Project",
    link: "https://jagadish-ecomarce.netlify.app/",
  },
  {
    id: 5,
    category: "react",
    img: "/bitreadly.png",
    name: "Bitreadly Design",
    link: "https://jagadish-bitradly.netlify.app/",
  },
  {
    id: 6,
    category: "react",
    img: "/culture-by-design.png",
    name: "Culture-By-Design",
    link: "https://jagadish-culture-by-design.netlify.app/",
  },
];
